name: Billing Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Tests on ${{ matrix.browser }}
        run: mvn clean test -Dbrowser=${{ matrix.browser }}

      - name: Archive HTML Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/report/html/

      - name: Archive JSON Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: json-reports
          path: target/report/json/

